baseurl = "http://blog.yadutaf.fr/"
name = "Yet another enthusiast blog!"
title = "Yet another enthusiast blog!"
languageCode = "en-us"
disqusShortname = "yadutaf"
theme = "angels-ladder"
paginate = 10

[Params]
subtitle = "There is no great achievement without great challenges."
twitter = "https://twitter.com/oyadutaf"
github = "https://github.com/yadutaf"
profile = "/images/profile.jpg"
copyright = "Jean-Tiare Le Bigot"
analytics = "UA-25807049-1"

